### ISSUE TITLE
What is the compatbility mode?

### ISSUE THREAD

**Issue by mwittig** [cognitivegears/node-milight-local-promise#1]
Can you please let me now for which scenario the compatbility mode is used for? Apparently, it involves sending 2-byte command sequences instead of 3-bytes.

**Comment by cognitivegears** [comment]
The 3-byte sequences do not seem to work, even though it matches all documentation.  The only reasoning that I can come up with is that there is something in the timing when proxying vs. directly sending the bytes that is causing the problem.  Regardless, changing to 2 byte sequence corrects the problem, but I left the original in as a compatibility mode mostly because I cannot figure out what I'm missing with the 3-byte sequences.
